
[workspace]
resolver = "2"

members = [
    "pdxsyn",
    "test_files",
    "mkprov_lib",
    "mkprov_eu4",
    "mkprov"
]

[workspace.dependencies]
derived-deref = "2.1.0"
itertools = "0.14.0"
thiserror = "2.0.9"
