[package]
name = "pdxsyn"
version = "0.0.2"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
derived-deref.workspace = true
itertools.workspace = true
slotmap = "1.0.7"
thiserror.workspace = true

[dev-dependencies]
test_files = { path = "../test_files" }
