[package]
name = "pdxsyn"
version = "0.0.1"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
derived-deref = "2.1.0"
thiserror = "2.0.9"

[dev-dependencies]
test_files = { path = "../test_files" }
