[package]
name = "pdxsyn"
version = "0.0.1"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
derived-deref = "2.1.0"
itertools = "0.14.0"
slotmap = "1.0.7"
thiserror = "2.0.9"

[dev-dependencies]
test_files = { path = "../test_files" }
