[package]
name = "paradox_file"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
serde.workspace = true
csv.workspace = true
encoding_rs_io.workspace = true
encoding_rs.workspace = true
thiserror.workspace = true
