[package]
name = "paradox_file"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
thiserror = "1.0.61"
clap = { version = "4.5.4", features = ["derive"] }
rand = "0.9.0-alpha.1"
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.14"