[package]
name = "mkprov"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "mkprov"
path = "main.rs"

[dependencies]
atty = "0.2.14"
clap = { version = "4.5.27", features = ["derive"] }
mod_workspace = { path = "../mod_workspace" }

[dev-dependencies]
tempdir = "0.3.7"
